
package com.ken.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoteServiceImplService", targetNamespace = "http://impl.webservice.ken.com/", wsdlLocation = "http://localhost:8080/ngback-ws/ws/RemoteService?wsdl")
public class RemoteServiceImplService
    extends Service
{

    private final static URL REMOTESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName REMOTESERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.ken.com/", "RemoteServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ngback-ws/ws/RemoteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        REMOTESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RemoteServiceImplService() {
        super(__getWsdlLocation(), REMOTESERVICEIMPLSERVICE_QNAME);
    }

    public RemoteServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTESERVICEIMPLSERVICE_QNAME, features);
    }

    public RemoteServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, REMOTESERVICEIMPLSERVICE_QNAME);
    }

    public RemoteServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTESERVICEIMPLSERVICE_QNAME, features);
    }

    public RemoteServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRemoteService
     */
    @WebEndpoint(name = "RemoteServiceImplPort")
    public IRemoteService getRemoteServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.ken.com/", "RemoteServiceImplPort"), IRemoteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRemoteService
     */
    @WebEndpoint(name = "RemoteServiceImplPort")
    public IRemoteService getRemoteServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.ken.com/", "RemoteServiceImplPort"), IRemoteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw REMOTESERVICEIMPLSERVICE_EXCEPTION;
        }
        return REMOTESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
